import { ArrowUpRight, CheckCircle2, ChevronRight, Clock3, MoreHorizontal, ShieldAlert, Sparkles, TrendingUp, XCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { AppShell, NewInspectionButton } from "@/components/AppShell";

const stats = [
  { label: "Total inspections", value: "1,284", change: "+12.8%", note: "vs. last month", icon: TrendingUp, tone: "cyan" },
  { label: "Compliant", value: "1,106", change: "86.1%", note: "of all inspections", icon: CheckCircle2, tone: "success" },
  { label: "Needs review", value: "96", change: "7.5%", note: "flagged for attention", icon: Clock3, tone: "amber" },
  { label: "Non-compliant", value: "82", change: "6.4%", note: "requires action", icon: XCircle, tone: "danger" },
];

const inspections = [
  { id: "PS-240819-084", name: "Golden Grains — Basmati Rice", time: "Today, 10:42 AM", inspector: "AS", status: "Compliant", confidence: "94%", tone: "success" },
  { id: "PS-240819-083", name: "PureDrop — Mineral Water", time: "Today, 09:18 AM", inspector: "RK", status: "Needs review", confidence: "71%", tone: "amber" },
  { id: "PS-240818-082", name: "Harvest Home — Wheat Flour", time: "Yesterday, 04:36 PM", inspector: "AS", status: "Non-compliant", confidence: "98%", tone: "danger" },
  { id: "PS-240818-081", name: "Sunrise — Turmeric Powder", time: "Yesterday, 02:11 PM", inspector: "MP", status: "Compliant", confidence: "96%", tone: "success" },
];

const toneMap: Record<string, { text: string; bg: string; icon: string }> = {
  cyan: { text: "text-packsure-amber", bg: "bg-packsure-amber/10", icon: "bg-packsure-amber/15" },
  success: { text: "text-packsure-success", bg: "bg-packsure-success/10", icon: "bg-packsure-success/15" },
  amber: { text: "text-packsure-amber", bg: "bg-packsure-amber/10", icon: "bg-packsure-amber/15" },
  danger: { text: "text-packsure-danger", bg: "bg-packsure-danger/10", icon: "bg-packsure-danger/15" },
};

function StatusPill({ status, tone }: { status: string; tone: string }) {
  const style = toneMap[tone];
  return <span className={`inline-flex items-center gap-1.5 rounded-sm border border-current px-2 py-1 font-mono-display text-[9px] font-medium uppercase tracking-[0.08em] ${style.bg} ${style.text}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>;
}

export default function Dashboard() {
  return <AppShell><div className="mx-auto max-w-[1440px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><div className="mb-2 flex items-center gap-2 font-mono-display text-[10px] uppercase tracking-[0.18em] text-packsure-amber"><span className="h-1.5 w-1.5 rounded-full bg-packsure-amber" />Tuesday, August 20, 2024</div><h1 className="font-display text-3xl font-bold uppercase tracking-[0.01em] text-white sm:text-4xl">Good morning, Ananya<span className="text-packsure-amber">.</span></h1><p className="mt-2 text-sm text-slate-200">Here’s what’s happening across your inspection workspace.</p></div><NewInspectionButton /></div>
    <section className="mt-9 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, change, note, icon: Icon, tone }) => { const style = toneMap[tone]; return <div key={label} className="group rounded-sm border border-white/[0.12] bg-packsure-panel p-5 shadow-panel transition-colors hover:border-white/[0.25]"><div className="flex items-start justify-between"><span className={`flex h-9 w-9 items-center justify-center rounded-sm ${style.icon} ${style.text}`}><Icon className="h-[18px] w-[18px]" strokeWidth={1.8} /></span><MoreHorizontal className="h-4 w-4 text-emerald-200" /></div><p className="mt-5 text-[11px] font-semibold text-slate-200">{label}</p><div className="mt-1 flex items-baseline gap-2"><span className="text-3xl font-extrabold tracking-[-0.05em] text-white">{value}</span><span className={`text-[10px] font-bold ${style.text}`}>{change}</span></div><p className="mt-1 text-[10px] text-emerald-200/80">{note}</p></div> })}</section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_0.75fr]">
      <section className="overflow-hidden rounded-sm border border-white/[0.12] bg-packsure-panel shadow-panel"><div className="flex items-center justify-between border-b border-white/[0.09] px-5 py-5 sm:px-6"><div><h2 className="text-sm font-extrabold text-white">Recent inspections</h2><p className="mt-1 text-[11px] text-emerald-200/85">Your latest field activity</p></div><Link to="/history" className="flex items-center gap-1 text-[11px] font-bold text-packsure-amber hover:text-white">View all <ArrowUpRight className="h-3.5 w-3.5" /></Link></div><div className="divide-y divide-white/[0.08]">{inspections.map((inspection) => <Link to="/result" key={inspection.id} className="group flex items-center gap-3 px-5 py-4 transition-colors hover:bg-white/[0.04] sm:gap-4 sm:px-6"><div className="hidden h-10 w-10 shrink-0 items-center justify-center rounded-sm border border-white/20 bg-[#19383a] text-[10px] font-bold text-emerald-200 sm:flex">{inspection.name.split(" ")[0].slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-xs font-bold text-white group-hover:text-packsure-amber">{inspection.name}</p><StatusPill status={inspection.status} tone={inspection.tone} /></div><div className="mt-1.5 flex flex-wrap items-center gap-2 font-mono-display text-[9px] text-slate-200"><span>{inspection.id}</span><span className="text-packsure-amber/60">•</span><span>{inspection.time}</span></div></div><div className="hidden text-right sm:block"><p className="font-mono-display text-[10px] font-bold text-white">{inspection.confidence}</p><p className="mt-1 text-[9px] text-emerald-200/80">confidence</p></div><ChevronRight className="h-4 w-4 shrink-0 text-emerald-300 transition-transform group-hover:translate-x-0.5 group-hover:text-packsure-amber" /></Link>)}</div></section>
      <section className="rounded-sm border border-white/[0.12] bg-packsure-panel p-5 shadow-panel sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-sm font-extrabold text-white">Compliance pulse</h2><p className="mt-1 text-[11px] text-emerald-200/85">Last 7 days</p></div><span className="rounded-sm bg-packsure-amber/10 p-2 text-packsure-amber"><Sparkles className="h-4 w-4" /></span></div><div className="mt-8 flex items-end justify-between gap-2"><div><p className="text-4xl font-extrabold tracking-[-0.06em] text-white">86.1<span className="text-xl text-packsure-amber">%</span></p><p className="mt-1 flex items-center gap-1 text-[10px] font-bold text-packsure-success"><TrendingUp className="h-3 w-3" /> 4.2% <span className="font-normal text-emerald-200">this week</span></p></div><div className="flex h-20 items-end gap-1.5">{[42, 56, 48, 70, 63, 82, 74].map((height, index) => <div key={index} className="group relative w-3 rounded-t bg-packsure-amber/20" style={{ height: `${height}%` }}><div className="absolute inset-x-0 bottom-0 rounded-t bg-packsure-amber transition-all group-hover:bg-packsure-amber" style={{ height: `${Math.min(height + 15, 100)}%` }} /></div>)}</div></div><div className="mt-8 space-y-3 border-t border-white/[0.08] pt-5"><div className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2 text-slate-200"><span className="h-2 w-2 rounded-full bg-packsure-success" />Compliant</span><span className="font-bold text-white">86.1%</span></div><div className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2 text-slate-200"><span className="h-2 w-2 rounded-full bg-packsure-amber" />Needs review</span><span className="font-bold text-white">7.5%</span></div><div className="flex items-center justify-between text-[11px]"><span className="flex items-center gap-2 text-slate-200"><span className="h-2 w-2 rounded-full bg-packsure-danger" />Non-compliant</span><span className="font-bold text-white">6.4%</span></div></div></section>
    </div>
    <section className="mt-5 grid gap-5 md:grid-cols-2"><div className="flex items-center gap-4 rounded-sm border border-packsure-amber/25 bg-[#161f22] p-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-sm bg-packsure-amber/15 text-packsure-amber"><ShieldAlert className="h-5 w-5" /></div><div className="min-w-0"><p className="text-xs font-extrabold text-white">12 inspections need your attention</p><p className="mt-1 text-[11px] leading-5 text-slate-200">Review low-confidence fields before end of day.</p></div><Link to="/history" className="ml-auto shrink-0 text-emerald-300 hover:text-packsure-amber"><ChevronRight className="h-5 w-5" /></Link></div><div className="flex items-center gap-4 rounded-sm border border-packsure-amber/25 bg-[#0e2023] p-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-sm bg-packsure-amber/15 text-packsure-amber"><Sparkles className="h-5 w-5" /></div><div className="min-w-0"><p className="text-xs font-extrabold text-white">Your AI accuracy is up 4.2%</p><p className="mt-1 text-[11px] leading-5 text-slate-200">PackSure is learning from your verified decisions.</p></div><Link to="/report" className="ml-auto shrink-0 text-emerald-300 hover:text-packsure-amber"><ChevronRight className="h-5 w-5" /></Link></div></section>
  </div></AppShell>;
}
