import { ArrowRight, Check, ChevronRight, FileCheck2, ScanLine, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { Brand } from "@/components/AppShell";

export default function Index() {
  return (
    <div className="relative min-h-screen overflow-x-hidden bg-packsure-ink text-white">
                  <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-4 py-5 sm:px-6 sm:py-6 lg:px-10">
        <Brand />
        <nav className="hidden items-center gap-8 text-sm font-semibold text-emerald-100 md:flex"><Link to="/#workflow" className="transition-colors hover:text-white">How it works</Link><Link to="/#security" className="transition-colors hover:text-white">Security</Link><Link to="/#footer" className="transition-colors hover:text-white">Contact</Link></nav>
        <div className="flex items-center gap-3"><Link to="/dashboard" className="hidden px-3 py-2 text-sm font-bold text-white transition-colors hover:text-packsure-amber sm:block">Sign in</Link><Link to="/dashboard" className="inline-flex items-center gap-2 rounded-sm border border-white/20 bg-white/[0.08] px-3 py-2.5 text-xs font-bold text-white transition-colors hover:border-packsure-amber/40 hover:bg-packsure-amber/10 sm:px-3.5"><span className="sm:hidden">Open</span><span className="hidden sm:inline">Open workspace</span><ArrowRight className="h-3.5 w-3.5 text-packsure-amber" /></Link></div>
      </header>

      <main className="relative z-10 mx-auto max-w-7xl px-4 pb-16 pt-10 sm:px-6 sm:pb-20 sm:pt-12 lg:px-10 lg:pb-28 lg:pt-20">
        <section className="grid items-center gap-12 sm:gap-14 lg:grid-cols-[0.92fr_1.08fr] lg:gap-14">
          <div>
            <div className="mb-7 inline-flex items-center gap-2 rounded-sm border-l-2 border border-packsure-amber/30 bg-packsure-amber/[0.1] px-3 py-1.5 font-mono-display text-[10px] font-bold uppercase tracking-[0.15em] text-packsure-amber"><span className="h-1.5 w-1.5 rounded-full bg-packsure-amber shadow-[0_0_10px_#f8bb59]" />AI inspection intelligence</div>
            <h1 className="max-w-xl text-balance font-display text-[clamp(3rem,11vw,6rem)] font-bold uppercase leading-[0.88] tracking-[0.005em]">Scan. Verify.<br /><span className="text-packsure-amber">Detect. Report.</span></h1>
            <p className="mt-6 max-w-lg text-base leading-7 text-emerald-100 sm:mt-7 sm:text-lg">The faster, smarter way to inspect packaged commodities. PackSure turns every label into a clear compliance decision.</p>
            <div className="mt-9 flex flex-wrap items-center gap-3"><Link to="/upload" className="inline-flex h-12 items-center gap-3 rounded-sm bg-packsure-amber px-5 text-sm font-extrabold text-packsure-ink  transition-transform hover:-translate-y-0.5">Start an inspection <ArrowRight className="h-4 w-4" /></Link><Link to="/dashboard" className="inline-flex h-12 items-center gap-2 rounded-sm border border-white/20 px-5 text-sm font-bold text-white transition-colors hover:border-white/40 hover:bg-white/[0.08]">View dashboard <ChevronRight className="h-4 w-4 text-emerald-200" /></Link></div>
            <div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold text-emerald-200"><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-packsure-success" />Built for inspectors</span><span className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-packsure-amber" />AI-assisted accuracy</span></div>
          </div>

          <div className="relative mx-auto w-full max-w-[590px] lg:ml-auto">
            <div className="relative animate-float overflow-hidden rounded-sm border border-white/20 bg-packsure-panel shadow-panel">
              <div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div className="flex items-center gap-2.5"><span className="flex h-7 w-7 items-center justify-center rounded-sm bg-packsure-amber/15 text-packsure-amber"><ScanLine className="h-3.5 w-3.5" /></span><span className="text-xs font-bold">Live inspection</span></div><span className="font-mono-display text-[9px] font-bold uppercase tracking-widest text-emerald-300">PS-240819-084</span></div>
              <div className="grid gap-0 sm:grid-cols-[1.08fr_0.92fr]">
                <div className="relative min-h-[300px] overflow-hidden border-b border-white/10 bg-[#101d20] p-5 sm:min-h-[330px] sm:p-7 sm:border-b-0 sm:border-r"><div className="absolute inset-0 opacity-30 grid-glow" /><div className="cut-lines relative mx-auto flex h-[230px] max-w-[275px] sm:h-[260px] flex-col justify-between rounded-md border border-white/25 bg-[#f2efe5] p-5 text-[#1d2827] shadow-[8px_10px_0_rgba(0,0,0,0.28)] rotate-[-3deg]"><div><div className="flex items-start justify-between"><div className="h-7 w-7 rounded bg-[#f0b449]" /><span className="font-mono-display text-[8px] font-bold">PACKAGED<br />COMMODITY</span></div><div className="mt-10 text-[21px] sm:mt-12 sm:text-[23px] font-black leading-none tracking-[-0.08em]">GOLDEN<br />GRAINS</div></div><div className="border-t border-[#1d2827]/20 pt-3 font-mono-display text-[9px] font-semibold leading-4">NET QTY: 500 g<br />MRP ₹ 84.00 (incl. of all taxes)<br />BATCH: GG2408A</div></div><div className="absolute left-1/2 top-0 h-28 w-px bg-gradient-to-b from-transparent via-packsure-amber to-transparent animate-scan-line" /></div>
                <div className="p-5 sm:p-6"><div className="flex items-center justify-between"><span className="font-mono-display text-[9px] font-bold uppercase tracking-[0.15em] text-emerald-300">Analysis</span><span className="flex items-center gap-1.5 text-[10px] font-bold text-packsure-success"><span className="h-1.5 w-1.5 rounded-full bg-packsure-success" />Complete</span></div><div className="mt-5 flex items-center gap-3 rounded-sm border border-packsure-success/20 bg-packsure-success/[0.08] p-3"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-packsure-success/15 text-packsure-success"><Check className="h-4 w-4" strokeWidth={3} /></div><div><p className="text-xs font-extrabold text-packsure-success">Compliant</p><p className="mt-0.5 font-mono-display text-[9px] font-semibold text-emerald-200">94% confidence</p></div></div><div className="mt-6 space-y-4">{[["MRP", "₹ 84.00", "99%"], ["Net quantity", "500 g", "97%"], ["Manufacturer", "Golden Grains Co.", "91%"], ["Date info", "EXP 08/2025", "89%"]].map(([label, value, score]) => <div key={label}><div className="flex items-center justify-between text-[10px]"><span className="text-emerald-200">{label}</span><span className="font-bold text-white">{value}</span></div><div className="mt-1.5 flex items-center gap-2"><div className="h-1 flex-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-packsure-amber" style={{ width: score }} /></div><span className="font-mono-display text-[8px] font-bold text-packsure-amber">{score}</span></div></div>)}</div><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-sm border border-white/20 py-2.5 text-[10px] font-bold text-white transition-colors hover:bg-white/[0.08]"><FileCheck2 className="h-3.5 w-3.5" />View full report</button></div>
              </div>
            </div>
            <div className="absolute -right-3 top-16 hidden rounded-sm border border-packsure-amber/20 bg-[#102c2e] px-3 py-2 shadow-xl sm:block"><p className="font-mono-display text-[9px] font-bold text-packsure-amber">AUTO-DETECTED</p><p className="mt-1 text-[10px] font-bold text-white">4 fields verified</p></div>
          </div>
        </section>

        <section id="workflow" className="mt-20 border-t border-white/10 pt-8 sm:mt-24"><div className="grid gap-8 md:grid-cols-3"><div><p className="font-mono-display text-[10px] font-bold uppercase tracking-[0.2em] text-packsure-amber">01 / Capture</p><p className="mt-3 text-sm font-bold text-white">One photo is all it takes</p><p className="mt-2 text-xs leading-5 text-slate-200">Upload a label image from the field. No forms, no manual data entry.</p></div><div><p className="font-mono-display text-[10px] font-bold uppercase tracking-[0.2em] text-packsure-amber">02 / Understand</p><p className="mt-3 text-sm font-bold text-white">AI reads every detail</p><p className="mt-2 text-xs leading-5 text-slate-200">Structured fields, confidence scores, and evidence keep every decision auditable.</p></div><div id="security"><p className="font-mono-display text-[10px] font-bold uppercase tracking-[0.2em] text-packsure-amber">03 / Act</p><p className="mt-3 text-sm font-bold text-white">Report with confidence</p><p className="mt-2 text-xs leading-5 text-slate-200">Generate a clear, inspection-ready report in seconds and keep your history organized.</p></div></div></section>
      </main>
      <footer id="footer" className="relative z-10 border-t border-white/[0.07] px-4 py-6 sm:px-6 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-[10px] font-semibold text-emerald-300 sm:flex-row"><span>© 2024 PackSure Intelligence</span><span className="font-mono-display font-bold uppercase tracking-[0.14em]">Trust, verified.</span></div></footer>
    </div>
  );
}
